django_assignments/secrets/apps/main_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout'),
]

django_assignments/secrets/apps/sercrets_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^like/(?P<secret_id>\d+)$', views.like, name = 'like'),
    url(r'^delete/(?P<secret_id>\d+)$', views.delete, name = 'delete'),
]

django_assignments/secrets/apps/users_app/urls.py
from django.conf.urls import url
from . import views
from .models import User

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = 'create'),
]

django_assignments/secrets/secrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main_app.urls', namespace='users')),
    url(r'^secrets/', include('apps.sercrets_app.urls', namespace='secrets')),
]

django_assignments/secrets/apps/sercrets_app/models.py
from __future__ import unicode_literals
from ..main_app.models import User
from django.db import models

# Create your models here.
class Secret(models.Model):
    content = models.CharField(max_length=255)
    user = models.ForeignKey(User, related_name = 'secret_creator')
    likes = models.ManyToManyField(User, related_name = 'user_likes')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

django_assignments/secrets/apps/main_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'main_app/index.html')

def register(request):
    response = User.objects.add_user(request.POST)
    if response['status']:
        request.session['user_id'] = response['new_user'].id
        request.session['user_fname'] = response['new_user'].first_name
        request.session['user_lname'] = response['new_user'].last_name
        return redirect('secrets:index')
    else:
        for error in response['errors']:
            messages.error(request, error)
    return redirect('users:index')

def login(request):
    response = User.objects.check_user(request.POST)
    if response['status']:
        request.session['user_id'] = response['loggedin_user'].id
        request.session['user_fname'] = response['loggedin_user'].first_name
        request.session['user_lname'] = response['loggedin_user'].last_name
        return redirect('secrets:index')
    else:
        for error in response['errors']:
            messages.error(request, error)
    return redirect('users:index')

def success(request):
    return render(request, 'main_app/success.html')

def logout(request):
    request.session.clear()
    return redirect('users:index')

django_assignments/secrets/apps/sercrets_app/views.py
from django.shortcuts import render, redirect
from ..main_app.models import User
from .models import Secret
# Create your views here.
def index(request):
    context = {
        'secrets': Secret.objects.all(),
        'user': User.objects.get(id=request.session['user_id'])
    }

    return render(request, 'sercrets_app/index.html', context)

def create(request):
    user = User.objects.get(id=request.session['user_id'])
    Secret.objects.create(content=request.POST['secret'], user=user)
    return redirect('secrets:index')

def like(request, secret_id):
    user = User.objects.get(id=request.session['user_id'])
    secret = Secret.objects.get(id=secret_id)
    secret.likes.add(user)
    return redirect('secrets:index')

def delete(request, secret_id):
    Secret.objects.get(id=secret_id).delete()
    return redirect('secrets:index')

django_assignments/secrets/apps/main_app/templates/main_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Registration</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'main_app/style/index.css' %}" media="screen" title="no title">
  </head>
  <body>
    <div class="container">
      {% if messages %}
          {% for message in messages %}
            <p>
              {{ message }}
            </p>
            {% endfor %}
        {% endif %}
      <div class="registration">
        <form class="" action="/register" method="post">
          {% csrf_token %}
          <p>
            First Name
            <input type="text" name="first_name" value="">
          </p>
          <p>
            Last Name
            <input type="text" name="last_name" value="">
          </p>
          <p>
            Email
            <input type="text" name="email" value="">
          </p>
          <p>
            Password
            <input type="password" name="password" value="">
          </p>
          <p>
            Password Confirmation
            <input type="password" name="confirm_password" value="">
          </p>
          <input type="submit" name="submit" value="Register">
        </form>
      </div><!-- end_of_regristration-->
      <div class="login">
        <form class="" action="/login" method="post">
          {% csrf_token %}
          <p>
            Email
            <input type="email" name="email" value="">
          </p>
          <p>
            Password
            <input type="password" name="password" value="">
          </p>
          <input type="submit" name="submit" value="Login">
        </form>
      </div><!-- end_of_login-->
    </div><!-- end_of_container-->
  </body>
</html>

django_assignments/secrets/apps/main_app/templates/main_app/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success Page</title>
  </head>
  <body>
    <div class="container">
      <h1>Welcome {{ request.session.user_fname }} {{ request.session.user_lname }}!</h1>
      <form class="" action="/logout" method="post">
        {% csrf_token %}
        <input type="submit" name="submit" value="Logout">
      </form>
    </div><!-- end_of_container-->
  </body>
</html>

django_assignments/secrets/apps/sercrets_app/templates/sercrets_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Users has Secrets</title>
  {% load humanize %}
</head>
<body>
  <div class="container">
    <h2>Hello {{ request.session.user_fname }}!</h2>
    <form action="{% url 'users:logout' %}" method='post'>
      {% csrf_token %}
      <input type="submit" value='Logout'>
    </form>
    <form action="{% url 'secrets:create' %}" method='post'>
      {% csrf_token %}
      <textarea name="secret" placeholder='Your secret here..........' rows="8" cols="40"></textarea>
      <input type="submit" value='Add Secret'>
    </form>
    <h4>Recent Secrets</h4>
    {% if secrets %}
      {% for secret in secrets %}
        <p>{{ secret.content }} ({{ secret.created_at|timesince }}) {{ secret.likes.count }} likes
          {% if user in secret.likes.all %}
            You liked this
          {% else %}
            <a href="{% url 'secrets:like' secret_id=secret.id%}">Like</a>
          {% endif %}
        {% if secret.user.id == request.session.user_id %}
          You posted this <a href="{% url 'secrets:delete' secret_id=secret.id %}">Delete</a>
        {% endif %}
        </p>
      {% endfor %}
    {% endif %}
  </div><!-- end_of_container-->
</body>
</html>