django_assignments/courses_and_login/apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^check$', views.check, name = 'check'),
    url(r'^show/(?P<course_id>)\d+', views.show_course, name = 'show_course'),
    url(r'^create$', views.create, name='create_course'),
    url(r'^delete/(?P<course_id>\d+)$', views.course_delete, name = 'delete_course'),
    url(r'^descripton/delete/(?P<descripton_id>\d+)$', views.descripton_delete),
    url(r'^user_course', views.user_to_course, name = 'add_user_to_course')
]

django_assignments/courses_and_login/apps/loginReg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout'),
]

django_assignments/courses_and_login/courses_and_login/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.loginReg.urls', namespace = 'users')),
    url(r'^courses/', include('apps.courses.urls', namespace = 'courses')),
]

django_assignments/courses_and_login/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models
from ..loginReg.models import User

# Create your models here.
class CourseManager(models.Manager):
    def add_user_to_course(self, postData):
        user = User.objects.get(id = postData['user_id'])
        course = self.get(id = postData['course_id'])
        course.users.add(user)

class Description(models.Model):
    content = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Course(models.Model):
    name = models.CharField(max_length=255)
    descripton = models.OneToOneField(Description)
    users = models.ManyToManyField(User, related_name = 'belongs_to')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = CourseManager()

django_assignments/courses_and_login/apps/loginReg/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def add_user(self, data):
        errors = []
        if len(data['first_name']) < 2:
            errors.append('First Name must be at least 2 characters long.')
        if len(data['last_name']) < 2:
            errors.append('Last Name must be at least 2 characters long.')
        if not data['email']:
            errors.append('Email field in required')
        if not EMAIL_REGEX.match(data['email']):
            errors.append('Enter a valid email')
        if len(data['password']) < 8:
            errors.append('Password must be at least 8 characters long.')
        if data['password'] != data['confirm_password']:
            errors.append('Password must match.')
        user = self.filter(email=data['email'])
        if user:
            errors.append('Email already exists')

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            new_user = self.create(first_name = data['first_name'], last_name = data['last_name'], email = data['email'], password = password)
            response['status'] = True
            response['new_user'] = new_user

        return response

    def check_user(self, data):
        user = self.filter(email=data['email'])
        errors = []
        response = {}
        if user:
            if bcrypt.hashpw(data['password'].encode(), user[0].password.encode()) == user[0].password.encode():
                print("It Matches!")
                response['status'] = True
                response['loggedin_user'] = user[0]
            else:
                print("It Does not Match :(")
                errors.append('Invalid email/password combination.')
                response['status'] = False
                response['errors'] = errors
        else:
            # email does not exits in DB
            errors.append('Email does not exist.')
            response['status'] = False
            response['errors'] = errors

        return response

class User(models.Model):
    first_name = models.CharField(max_length = 45)
    last_name = models.CharField(max_length = 45)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

django_assignments/courses_and_login/apps/courses/views.py
from django.shortcuts import render, redirect
from .models import Course, Description
from django.contrib import messages
from ..loginReg.models import User

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        anything = {
            'courses': Course.objects.all(),
            'users': User.objects.all(),
            'descriptons': Description.objects.all(),
        }
        return render(request, 'courses/index.html', anything)
    else:
        messages.error(request, 'Must be logged in to continue!')
        return redirect('users:index')

def create(request):
    descripton = Description.objects.create(content=request.POST['content'])
    Course.objects.create(name = request.POST['name'], descripton = descripton)
    return redirect('courses:index')

def course_delete(request, course_id):
    Course.objects.filter(descripton_id = course_id).delete()
    return redirect('courses:index')

def descripton_delete(request, descripton_id):
    Description.objects.filter(id = descripton_id).delete()
    return redirect('courses:index')

def show_course(request, course_id):
    print 'in show'
    context = {
        'course': course_id
    }
    return render(request, 'courses/show.html', context)

def check(request):
    print 'in check'
    return redirect('courses:show_course', course_id=2)

def user_to_course(request):
    if request.method == 'POST':
        print request.POST
        Course.objects.add_user_to_course(request.POST)
    return redirect('courses:index')

django_assignments/courses_and_login/apps/loginReg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from ..courses.models import Course, Description
# Create your views here.
def index(request):
    return render(request, 'loginReg/index.html')

def register(request):
    response = User.objects.add_user(request.POST)
    if response['status']:
        request.session['user_id'] = response['new_user'].id
        request.session['user_fname'] = response['new_user'].first_name
        request.session['user_lname'] = response['new_user'].last_name
        return redirect('courses:index')
    else:
        for error in response['errors']:
            messages.error(request, error)
    return redirect('users:index')

def login(request):
    response = User.objects.check_user(request.POST)
    if response['status']:
        request.session['user_id'] = response['loggedin_user'].id
        request.session['user_fname'] = response['loggedin_user'].first_name
        request.session['user_lname'] = response['loggedin_user'].last_name
        return redirect('courses:index')
    else:
        for error in response['errors']:
            messages.error(request, error)
    return redirect('users:index')

def success(request):
    anything = {
        'courses': Course.objects.all(),
        'users': User.objects.all(),
        'descriptons': Description.objects.all(),
    }
    return render(request, 'loginReg/success.html', anything)

def logout(request):
    request.session.clear()
    return redirect('users:index')

django_assignments/courses_and_login/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="{% url 'users:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="submit" value="Logout">
    </form>
    <form class="" action="{% url 'courses:create_course' %}" method="post">
      {% csrf_token %}
      <p>Course
        <input type="text" name="name" value="">
      </p>
      <p>
        <textarea name="content" rows="5" cols="20"></textarea>
      </p>
      <input type="submit" name="submit" value="Add">
    </form>
    <hr>
    {% for descripton in descriptons %}
      <p>
        {{ descripton.id }}
      </p>
    {% endfor %}
    {% if courses %}
      <ul>
        {% for course in courses %}
          <li>{{ course.id }} {{ course.name }} {{ course.descripton.content }}
            <ul>
              {% for user in course.users.all %}
                <li>{{ user.first_name }} {{ user.last_name }}</li>
              {% endfor %}
            </ul>
            <form class="" action="/delete/{{ course.id }}" method="post">
              {% csrf_token %}
              <input type="submit" name="submit" value="Delete course">
            </form>
            <form class="" action="/descripton/delete/{{ course.descripton.id }}" method="post">
              {% csrf_token %}
              <input type="submit" name="submit" value="Delete descripton">
            </form>
          </li>

          <hr>
          {% endfor %}
      </ul>
    {% endif %}
    <h1>Add user to course</h1>
    <form class="" action="{% url 'courses:add_user_to_course' %}" method="post">
      {% csrf_token %}
      <p>User</p>
      <select class="" name="user_id">
        {% for user in users %}
          <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
        {% endfor %}
      </select>
      <p>Course</p>
      <select class="" name="course_id">
        {% for course in courses %}
          <option value="{{ course.id }}">{{ course.name }} {{ course.id }}</option>
        {% endfor %}
      </select>
      <input type="submit" name="" value="Add">
    </form>
    <h1>Users courses</h1>
    <ul>
      {% for user in users %}
        <li>{{ user.first_name }} {{ user.last_name }}</li>
        <ul>
          {% for course in user.belongs_to.all %}
            <li>{{ course.name }}</li>
          {% endfor %}
        </ul>
      {% endfor %}
    </ul>
  </body>
</html>

django_assignments/courses_and_login/apps/courses/templates/courses/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{ course }}</h1>
  </body>
</html>

django_assignments/courses_and_login/apps/loginReg/templates/loginReg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Registration</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'main_app/style/index.css' %}" media="screen" title="no title">
  </head>
  <body>
    <div class="container">
      {% if messages %}
          {% for message in messages %}
            <p>
              {{ message }}
            </p>
            {% endfor %}
        {% endif %}
      <div class="registration">
        <form class="" action="{% url 'users:register' %}" method="post">
          {% csrf_token %}
          <p>
            First Name
            <input type="text" name="first_name" value="">
          </p>
          <p>
            Last Name
            <input type="text" name="last_name" value="">
          </p>
          <p>
            Email
            <input type="text" name="email" value="">
          </p>
          <p>
            Password
            <input type="password" name="password" value="">
          </p>
          <p>
            Password Confirmation
            <input type="password" name="confirm_password" value="">
          </p>
          <input type="submit" name="submit" value="Register">
        </form>
      </div><!-- end_of_regristration-->
      <div class="login">
        <form class="" action="{% url 'users:login' %}" method="post">
          {% csrf_token %}
          <p>
            Email
            <input type="email" name="email" value="">
          </p>
          <p>
            Password
            <input type="password" name="password" value="">
          </p>
          <input type="submit" name="submit" value="Login">
        </form>
      </div><!-- end_of_login-->
    </div><!-- end_of_container-->
  </body>
</html>

django_assignments/courses_and_login/apps/loginReg/templates/loginReg/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success Page</title>
  </head>
  <body>
    <div class="container">
      {% for user in users %}
        {% if user.last_name == 'Kim' %}
          <p>{{ user.first_name }}</p>
        {% else %}
          <p>{{ user.id }}</p>
        {% endif %}
      {% endfor %}
      <h1>Welcome {{ request.session.user_fname }} {{ request.session.user_lname }}!</h1>
      <form class="" action="/logout" method="post">
        {% csrf_token %}
        <input type="submit" name="submit" value="Logout">
      </form>
      <form class="" action="{% url 'courses:create_course' %}" method="post">
        {% csrf_token %}
        <p>Course
          <input type="text" name="name" value="">
        </p>
        <p>
          <textarea name="content" rows="5" cols="20"></textarea>
        </p>
        <input type="submit" name="submit" value="Add">
      </form>
      <hr>
      {% for descripton in descriptons %}
        <p>
          {{ descripton.id }}
        </p>
      {% endfor %}
      {% if courses %}
        <ul>
          {% for course in courses %}
            <li>{{ course.id }} {{ course.name }} {{ course.descripton.content }}
              <ul>
                {% for user in course.users.all %}
                  <li>{{ user.first_name }} {{ user.last_name }}</li>
                {% endfor %}
              </ul>
              <form class="" action="/delete/{{ course.id }}" method="post">
                {% csrf_token %}
                <input type="submit" name="submit" value="Delete course">
              </form>
              <form class="" action="/descripton/delete/{{ course.descripton.id }}" method="post">
                {% csrf_token %}
                <input type="submit" name="submit" value="Delete descripton">
              </form>
            </li>

            <hr>
            {% endfor %}
        </ul>
      {% endif %}
      <h1>Add user to course</h1>
      <form class="" action="{% url 'courses:add_user_to_course' %}" method="post">
        {% csrf_token %}
        <p>User</p>
        <select class="" name="user_id">
          {% for user in users %}
            <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
          {% endfor %}
        </select>
        <p>Course</p>
        <select class="" name="course_id">
          {% for course in courses %}
            <option value="{{ course.id }}">{{ course.name }} {{ course.id }}</option>
          {% endfor %}
        </select>
        <input type="submit" name="" value="Add">
      </form>
      <h1>Users courses</h1>
      <ul>
        {% for user in users %}
          <li>{{ user.first_name }} {{ user.last_name }}</li>
          <ul>
            {% for course in user.belongs_to.all %}
              <li>{{ course.name }}</li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
    </div><!-- end_of_container-->
  </body>
</html>