demos/.ajax_demo_redo/ajax_demo/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace = 'main')),
]

demos/.ajax_demo_redo/apps/first_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = 'create'),
]

demos/.ajax_demo_redo/apps/first_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length = 45)
    description = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

demos/.ajax_demo_redo/apps/first_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Course
from django.forms.models import model_to_dict

# Create your views here.
def index(request):
    print Course.objects.all(),
    context = {
        'courses':Course.objects.all(),
    }
    return render(request, 'first_app/index.html', context)

def create(request):
    if request.method == 'POST':
        course = Course.objects.create(name = request.POST['name'], description = request.POST['description'])
        print course
        return JsonResponse({'course': model_to_dict(course)})

demos/.ajax_demo_redo/apps/first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Ajax Demo</title>
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    {% load staticfiles %}
    <script src="{% static 'main/js/index.js' %}" type="text/javascript"></script>
  </head>
  <body>
    <div class="container">
      <h1>Ajax Demo</h1>
      <div class="courses">
        {% for course in courses %}
          <p>{{ course.name }}</p>
        {% endfor %}
      </div><!-- end_of_couses -->
      <p>{{ course }}</p>
      <form class="" action="{% url 'main:create' %}" method="post">
        {% csrf_token %}
        <p>Course: <input type="text" name="name" value=""></p>
        <p>Description: <input type="text" name="description" value=""></p>
        <p><input type="submit" name="" value="Add"></p>
      </form>
    </div><!-- end_of_container -->
  </body>
</html>