april_model_demo_two/apps/authors_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create$', views.create, name = 'create')
]

april_model_demo_two/apps/first_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = 'create')
]

april_model_demo_two/apps/publishers_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create$', views.create, name = 'create'),
    url(r'^bookToPub$', views.publishers_has_books, name = 'add_book_to_publisher')
]

april_model_demo_two/april_model_demo/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace = 'book')),
    url(r'^author/', include('apps.authors_app.urls', namespace = 'author')),
    url(r'^publisher/', include('apps.publishers_app.urls', namespace = 'publisher')),
]

april_model_demo_two/apps/authors_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length = 45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

april_model_demo_two/apps/first_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..authors_app.models import Author

# Create your models here.

class BookManager(models.Manager):
    def validateBook(self, postData):
        validation_errors = []
        print postData

        if not len(postData['title']):
            validation_errors.append('title is required')
        # if not len(postData['author']):
        #     validation_errors.append('author is required')

        response_to_views = {}

        if validation_errors:
        # failed validations
            response_to_views['status'] = False
            response_to_views['errors'] = validation_errors
        else:
            # passed validations/ create the book
            author = Author.objects.get(id = postData['author_id'])
            book = self.create(title = postData['title'], author = author)
            response_to_views['status'] = True
            response_to_views['book'] = book

        return response_to_views

class Book(models.Model):
    title = models.CharField(max_length = 45)
    author = models.ForeignKey(Author, related_name = 'wrote')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    run = BookManager()

april_model_demo_two/apps/publishers_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..first_app.models import Book

# Create your models here.
class PublisherManager(models.Manager):
    def add_publisher(self, postData):
        if not len(postData['name']):
            # failed validations
            return (False, 'name is required!')
        else:
            # create our publisher
            publisher = self.create(name = postData['name'])
            return (True, publisher)

    def add_book_to_publisher(self, postData):
        print postData
        publisher = self.get(id = postData['publisher_id'])
        book = Book.run.get(id = postData['book_id'])
        publisher.books.add(book)

class Publisher(models.Model):
    name = models.CharField(max_length = 45)
    books = models.ManyToManyField(Book, related_name = 'published_by')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = PublisherManager()

april_model_demo_two/apps/authors_app/views.py
from django.shortcuts import render, redirect
from .models import Author

# Create your views here.
def create(request):
    # do validations
    if request.method == 'POST':
        Author.objects.create(name = request.POST['name'])

    return redirect('book:index')

april_model_demo_two/apps/first_app/views.py
from django.shortcuts import render, redirect
from .models import Book
from django.contrib import messages
from ..authors_app.models import Author
from ..publishers_app.models import Publisher

# Create your views here.
def index(request):
    # print Book.objects.all()
    context = {
        'all_books': Book.run.all(),
        'all_authors': Author.objects.all(),
        'all_publishers': Publisher.objects.all()
    }
    return render(request, 'first_app/index.html', context)

def create(request):
    if request.method == 'POST':
        print request.POST
        response_from_models = Book.run.validateBook(request.POST)
        # book = Book.objects.create(title = request.POST['title'], author = request.POST['author'])
        print response_from_models
        # did not pass validations(boolean)
        if not response_from_models['status']:
            for model_error in response_from_models['errors']:
                messages.error(request, model_error)
        else:
            print response_from_models['book']


    return redirect('book:index')

april_model_demo_two/apps/publishers_app/views.py
from django.shortcuts import render, redirect
from .models import Publisher
from django.contrib import messages

# Create your views here.
def create(request):
    print request.POST
    response = Publisher.objects.add_publisher(request.POST)
    print response
    if response[0] == False:
        messages.error(request, response[1])
    return redirect('book:index')

def publishers_has_books(request):
    print request.POST
    Publisher.objects.add_book_to_publisher(request.POST)

    return redirect('book:index')

april_model_demo_two/apps/first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      .error{
        color:red;
      }
      .book, .author, .publisher{
        display: inline-block;
        vertical-align: top;
        padding: 20px;
        border: 1px solid black;
      }
    </style>
  </head>
  <body>
    <div class="author">
      <h1>Add Author</h1>
      <form class="" action="{% url 'author:create' %}" method="post">
        {% csrf_token %}
        <p>Name: <input type="text" name="name" value=""></p>
        <input type="submit" name="" value="add author">
      </form>
      <h1>All authors</h1>
      <ul>
        {% for author in all_authors %}
          <li>{{ author.name }}</li>
          <ul>
            {% for book in author.wrote.all %}
              <li>{{ book.title }}</li>
              <ul>
                {% for publisher in book.published_by.all %}
                  <li>{{ publisher.name }}</li>
                {% endfor %}
              </ul>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
    </div><!-- end_of_author -->
    <div class="book">
      <h1>Add Book</h1>
      <form class="" action="{% url 'book:create' %}" method="post">
        {% csrf_token %}
        <p>Title: <input type="text" name="title" value=""></p>
        <p>Author:
          <select class="" name="author_id">
            {% for author in all_authors %}
              <option value="{{ author.id }}">{{ author.name }}</option>
            {% endfor %}
          </select></p>
          <input type="submit" name="" value="add book">
      </form>
      {% for message in messages %}
        <p class='error'>{{ message }}</p>
      {% endfor %}
      <h1>Books</h1>
      <ul>
        {% for book in all_books %}
          <li>{{ book.title }} written by: {{ book.author.name }}</li>
          <ul>
            {% for publisher in book.published_by.all %}
              <li>{{ publisher.name }}</li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
    </div><!-- end_of_book -->
    <div class="publisher">
      <h1>Add publisher</h1>
      <form class="" action="{% url 'publisher:create' %}" method="post">
        {% csrf_token %}
        <p>Name: <input type="text" name="name" value=""></p>
        <input type="submit" name="" value="Add publisher">
      </form>
      <h1>All Publishers</h1>
      <ul>
        {% for publisher  in all_publishers %}
          <li>{{ publisher.name }}</li>
          <ul>
            {% for book in publisher.books.all %}
              <li>{{ book.title }}</li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
      <h1>Add book to publisher</h1>
      <form class="" action="{% url 'publisher:add_book_to_publisher' %}" method="post">
        {% csrf_token %}
        <p>Book:
          <select class="" name="book_id">
            {% for book in all_books %}
              <option value="{{ book.id }}">{{ book.title }}</option>
            {% endfor %}
          </select>
        </p>
        <p>Publisher:
          <select class="" name="publisher_id">
            {% for publisher in all_publishers %}
              <option value="{{ publisher.id }}">{{ publisher.name }}</option>
            {% endfor %}
          </select>
        </p>
        <input type="submit" name="" value="add book to publisher">
      </form>
    </div><!-- end_of_publisher -->
  </body>
</html>